### ISSUE TITLE
Parameterize the interpolation format for the price in TOML

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/simulator#10]
e.g 
10:4,30:8 
TFT: 3 
0:0,10:4,30:8 
0:0,10:4,30:8,31:0

probably used from https://github.com/threefoldfoundation/simulator/blob/development/src/simulator/TFGridSimulator.cr#L82 @RafyAmgadBenjamin please check

**Comment by RafyAmgadBenjamin** [comment]
fixed 
but we didn't chage `nrnodes_new` as it depends on the `growth` value
