### ISSUE TITLE
don't use /sandbox, doesn't work on mac

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/simulator#8]
use more reasonable dir e.g /home/$USERNAME/sandbox/....

**Comment by RafyAmgadBenjamin** [comment]
### Fixed 
#### commite_id https://github.com/threefoldfoundation/simulator/commit/eb8c0ec2afe66ca9ea428da017bda47ebf36a13c
1. Make the export path as a parameter can be passed to simulator 
2. Make the default export_path relative to the user ~/sandbox
